### ISSUE TITLE
Build tool integration (examples only)

### ISSUE THREAD

**Issue by ben-manes** [square/javapoet#195]
Its probably worth showing a few examples of quick-n-dirty integration with build tools.  Plugins are more appropriate for mature libraries vs one-off usages. Otherwise users will be tempted to check in their generated code instead of learning their build tool properly.

A quick hack of Gradle integrated my usage easily (below). I think Maven might need to use a script plugin (e.g. GMaven), while ant/sbt/etc are more straightforward.

```groovy
sourceSets {
  javaPoet {
    java.srcDir 'src/javaPoet/java'
  }
  main {
    java.srcDir "${buildDir}/generated-sources/"
  }
}

plugins.withType(EclipsePlugin) {
  project.eclipse.classpath.plusConfigurations += [ configurations.javaPoetCompile ]
}

task javaPoetGenerate(type: JavaExec) {
  main = '...code generator...'
  classpath = sourceSets.javaPoet.runtimeClasspath
  args "${buildDir}/generated-sources/"
}

compileJava.dependsOn(javaPoetGenerate)

dependencies {
  javaPoetCompile "..."
}
```

**Comment by JakeWharton** [comment]
I think this might be a bit out of scope due to the sheer number of ways you can use this library. There's annotation processors, ant tasks, gradle tasks, gradle plugins, maven plugins, sbt plugins, buck tasks, pants tasks, standalone jars, intellij plugins, eclipse plugins, and I'm sure there's even more. Aside from the sheer diversity, usually these integrations are non-trivial to the point of requiring more fully fledged examples to look at.

It might be more useful to link to two or three projects which are using the library as concrete examples that people can build off of.

**Comment by ben-manes** [comment]
Yep, I agree (which is why I said a few examples and not full plugins). A link or two for pointers would be a nice addition imho.

**Comment by JakeWharton** [comment]
We're working on getting some projects converted before we release 1.0.

**Comment by ben-manes** [comment]
Okay, closing as I assume examples will be listed once the migrate completes

**Comment by tbroyer** [comment]
@ben-manes Your setup seems overly complicated to just tell Eclipse to use the generated source code from a Gradle run (i.e. without even configuring Eclipse to run the annotation processor itself) – that said, it seems like Gradle makes it overly complicated to add arbitrary source folders to an Eclipse `.classpath`, it's much easier with IDEA.
See also https://github.com/mkarneim/pojobuilder/wiki/Enabling-PojoBuilder-for-Eclipse-Using-Gradle for a no less complex setup but one that enables annotation processing right within Eclipse.
That being said, it's not that hard to configure things manually in your IDE (OK, maybe not that easy in Eclipse as you have to go pick the JARs of the processor path manually; in some cases it could be easier to configure a build command that just runs your build too to run the annotation processors, and add the output as a source folder) and keep your build scripts clean: cf. https://immutables.github.io/apt.html
Ideally, you'd have plugins in either the build tool or the IDE (or both) to help you set everything up. I bet we'll see things improve as the Java community is catching up with annotation processors (e.g. Takari is working with the Eclipse JDT team to make JDT-APT more reliable now that they use the JDT compiler for their regular Maven builds instead of javac; that should benefit all Eclipse users)

FYI, Maven+Eclipse just needs the m2e-apt plugin: https://marketplace.eclipse.org/content/m2e-apt

**Comment by ben-manes** [comment]
Well the Eclipse part is just the plugin section, which is 3 lines. The rest is to inform Gradle to generate the code during its build and make the output a source file for the compile target. That's more complicated because I don't want the code generator as part of the distribution and need to compile & execute it. The alternative would have been to generate the code and check it in as source, which I prefer not to do but would have had it taken more than a few minutes to configure Gradle. I don't recall Maven being much better, except generally being harder to do ad hoc without scriptlets or other non-plugin hacks.

I'm confused by the comments on annotation processor (where?) or why one would manually modify the Eclipse files (which is easy to do, but not necessary). The Eclipse / IDEA integration is pretty minimal, its all the trouble one goes through to break sourceSets and modules apart in Gradle that is both much nicer than Maven, but so much unnecessary work compared to Blaze (or its clones Pants & Buck).

I've had to go through the same Gradle hassle when working on other code generators (jOOQ, jsonSchema2pojo) plugins and when building micro-service style modules (api/impl). Supposedly the [new configuration model](http://www.gradle.org/roadmap#configuration) will be simpler and faster. It may even be Blaze-like, though I haven't looked at the pre-release yet.

**Comment by tbroyer** [comment]
Ah, sorry, given that all projects that I know of that use (or could use) JavaPoet (or JavaWriter) are annotation processors, I jumped to conclusions and somehow thought I was commenting on such a project (and totally forgot all those other code generators – Wire, JOOQ, etc.)

So, if we were on an issue about an annotation processor or other code generator project, it would make sense to document how to use it with various build tools and IDEs (and automatically configure IDEs from the build script when prossible).
But JavaPoet is just a library to generate Java code, that could be used in many situations, and having documentation about how some of those tools could be integrated in some build tools and IDEs is completely out of scope (from my PoV): Wire should document it on their side, JOOQ should document it on their side, etc.

**Comment by ben-manes** [comment]
I don't disagree, and closed the issue. However, there are many codegen cases in which usage is internal and not for external users of the library. In my case to generate optimal classes to minimize memory. A very light overview of integration, like merely links to successful usages, aid developers using JavaPoet directly. This wasn't meant to be a time consuming or all encompassing request, just a few pointers if needed for common integration issues.

**Comment by Hollerweger** [comment]
I'm working on an IDEA /Android Studio Project and would need a similar gradle javapoet setup. @ben-manes Do you have any example project?

**Comment by ben-manes** [comment]
You can see my [build](https://github.com/ben-manes/caffeine/blob/master/caffeine/build.gradle).

You may need to add it as a source in idea, which I haven't tested for a while. If so that would load k like
```
idea.module {
  scopes.PROVIDED.plus += [ configurations.javaPoet ]
}
```

**Comment by Hollerweger** [comment]
Thanks, I'm not sure how javaPoetCompile and compileJavaPoetJava is resolved and if I even need it.
The code generation should be invoked by compileJava.dependsOn only or?

**Comment by ben-manes** [comment]
The Java plugin creates them automatically from the sourceSet. In my case there are dependencies used by the code generator but the output is dependent ency free. You can invoke the task however you'd like and I put it in the compilation flow.
