### ISSUE TITLE
fold many imports of the same package into a single statement

### ISSUE THREAD

**Issue by glockenstein** [square/javapoet#222]
please add an option to fold many imports like:
```
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.Table;
```
into a single one (import javax.persistence.* here),
the number of classes when it starts folding should be a configuration option

**Comment by swankjesse** [comment]
Wildcard imports are very dangerous to use in generated code. Because we don't know the other classes in the package, they can cause an import to be ambiguous.

Our philosophy on imports is this: prefer to be completely unambiguous, even if the cost is redundancy.

**Comment by robertvazan** [comment]
I would like this reopened. I have a research app that aids in its own development by generating some of its own code. This code is however also sometimes modified manually or by IDE refactorings (the app is smart enough not to destroy the manual edits). After manual edit, IDE reformats the file upon save, including folding similar imports into wildcards. It would be helpful to have JavaPoet generate code with the same conventions as the IDE is configured to use, so that the code does not bounce forth and back between two styles.
