### ISSUE TITLE
Checkstyle issue

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#319]
The Check Configuration contains the `NewlineAtEndOfFile` rule, but none of the files in `src/main/java` ends with a new line char. Either add the missing EOL char or remove the rule?

**Comment by JakeWharton** [comment]
They all end with a newline. GitHub omits displaying it, but it would show "No newline at end of file" if it was missing. You can also inspect it in a text editor:

<img width="309" alt="screen shot 2015-08-05 at 10 22 49 am" src="https://cloud.githubusercontent.com/assets/66577/9088023/fc810c2a-3b5b-11e5-89c7-329f514f7a66.png">

**Comment by sormuras** [comment]
http://stackoverflow.com/a/15433548/1431016

It's a Unix/Windows conversion thing. With the `name="lineSeparator" value="lf"` the Surefire/Checkstyle target does not break the Maven install run.

**Comment by JakeWharton** [comment]
I see.

**Comment by tbroyer** [comment]
Apparently, the best practice on Windows is to set `core.autocrlf` to `true` so that Git automatically translates between LF in the repo and CRLF in the working tree (ref: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#coreautocrlf-bWGI0)
That would fix the checkstyle as a side effect IIUC.

**Comment by swankjesse** [comment]
Seems like a Checkstyle issue if anything. No action for us to take here.
