### ISSUE TITLE
Extending/implementing imports of the same name results in a name clash

### ISSUE THREAD

**Issue by christianbreynolds** [square/javapoet#470]
If I try to make an interface that extends another imported interface of the same name, the produced code has a clash of names. For instance, if I were writing a Person interface in a package com.example, and wanted to extend another Person interface in org.sample, I might write:

```
ClassName name = ClassName.get("org.sample", "Person");
TypeSpec type = TypeSpec.interfaceBuilder("Person").addSuperinterface(name).build();
JavaFile file = JavaFile.builder("com.example", type).build();
```

However, the JavaFile outputs: 

```
package com.example;

import org.sample.Person;

interface Person extends Person {
}
```

which isn't correct unless the line reads `interface Person extends org.sample.Person`. The same occurs for classes, and for already existing types (i.e. `TypeSpec.classBuilder("ArrayList").addSuperinterface(ArrayList.class).build();` )

**Comment by tbroyer** [comment]
It looks like the test introduced in #471 passes only because the type is referenced (in the `Comparable<Taco>` superinterface). If you remove the reference to the type itself, then the bug is reproduced.

I've just been bitten by this, and am now trying to find the least ugly way to reference the type in the file.
