### ISSUE TITLE
Allow to specify file encoding

### ISSUE THREAD

**Issue by marschall** [square/javapoet#473]
Currently the file encoding is always the system default encoding. This is unreliable. It would be better to have a way to specify the encoding of the generated .java files.

**Comment by swankjesse** [comment]
Send a pull request?

**Comment by marschall** [comment]
Sure, give me a few days.

**Comment by hintzed** [comment]
I'd love to see this feature in the next release if possible. At the moment we need to work around this by changing the JVM encoding on startup. Thx!

**Comment by marschall** [comment]
@hintzed what source encoding do you require? On which platform are you?

**Comment by hintzed** [comment]
I'd like to achieve UTF-8 encoding for the generated sources. We develop on Windows using Eclipse, which we configure to use UTF-8 instead of the default windows-1252. Our build server runs on linux using UTF-8.

We use JavaPoet as part of a gradle build script, at the moment specifying _file.encoding_ explicitly for the JVM running the code generation task, which works, but ideally could be avoided.

**Comment by kkalisz** [comment]
HI, are there any plans to merge this ??

**Comment by sormuras** [comment]
It's already forced to `UTF-8`, not? See https://github.com/square/javapoet/pull/474#issuecomment-259326821

**Comment by swankjesse** [comment]
Yup. If you need another charset you lose out on some convenience APIs but you can still do everything.
