### ISSUE TITLE
ParameterSpec.addJavadoc may be usefull

### ISSUE THREAD

**Issue by tlevavasseur** [square/javapoet#495]
```
MethodSpec dismiss = MethodSpec.methodBuilder("dismiss")
    .addJavadoc("Some documentation")
    .addParameter(ParameterSpec.builder(String.class, "message")
        .addJavadoc("the message to send").build())
    .build();
```

would generate :

```
/**
 * Some documentation.
 * @param message the message to send.
 */
void dismiss(String message);
```

Note : the dot automatically added to the end of the @param doc line would be great.

**Comment by JakeWharton** [comment]
Automatically adding the dot is not smart since creating a multi-sentence
parameter description becomes asymmetric in punctuation.

Prior to 1.0 I suggested this very API and we rejected it because it seemed
like too much complexity at the time (of developing 1.0). I'm still
supportive of this and things like overloads of `addException` and
`returnType` which accept a description for the Javadoc.

**Comment by gk5885** [comment]
+1 to the FR.

-1 to adding the dot.

**Comment by swankjesse** [comment]
Let’s do it.
