### ISSUE TITLE
Nested Class Inside Interface Throws Unnecessary Exception

### ISSUE THREAD

**Issue by commonsguy** [square/javapoet#531]
A minor nit, since the workaround is easy, but...

I am generating a nested class inside an interface using JavaPoet 1.8.0:

```java
public interface Vehicle {
  class Deserializer extends TypenameBasedDeserializer<Vehicle> {
    public Deserializer() {
      map("Car", Car.class);
      map("Boat", Boat.class);
    }
  }
}
```

If for the `TypeSpec.Builder` for the nested `Deserializer` class, I either skip `addModifiers()` entirely or use `addModifiers(Modifier.PUBLIC)`, I get an exception:

```
java.lang.IllegalArgumentException: INTERFACE Vehicle.Deserializer requires modifiers [public, static]
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.TypeSpec$Builder.addType(TypeSpec.java:567)
```

The workaround is to use `addModifiers(Modifier.PUBLIC, Modifier.STATIC)`, as the exception suggests. However, since the resulting code does not *use* those modifiers, it seems a bit harsh to throw an exception forcing us to add modifiers, only to have them be discarded.

**Comment by commonsguy** [comment]
Never mind. This is an extension of [the rules for interfaces cited here](https://github.com/square/javapoet#interfaces). Still seems harsh, though.

**Comment by JakeWharton** [comment]
As the support for other visibilities is added to Java versions (like
private for instance and static methods in Java 9) having these explicitly
specified might actually wind up being a benefit.

**Comment by swankjesse** [comment]
We’re balancing between being a thing that models the AST and a thing that formats strings. This particular decision is surprising because it’s enforcing strict AST rules and then exploiting a rule in the compiler where unnecessary keywords aren’t emitted.

In theory this strategy is good for composability. Imagine you made a factory method that returns FieldSpecs that define constants (`newConstant("CONTENT_TYPE", "application/json")`) and then you can use those things anywhere you want and JavaPoet emits the right modifiers for the context.

In practice if people are thinking about JavaPoet as a thing that formats strings then we could make it dumber and less surprising.

No urgency on my end to change our current behavior!
