### ISSUE TITLE
Q: modifier required "ABSTRACT" and "PUBLIC"

### ISSUE THREAD

**Issue by chmuche** [square/javapoet#532]
Hello, I start a new project and I use JavaPoet to generate class and every is fine for me :smile: 
But when I started to create my interface I have an error produce by this method : 

TypeSpec.java :: line 539
```
public Builder addMethod(MethodSpec methodSpec) {
      if (kind == Kind.INTERFACE) {
        requireExactlyOneOf(methodSpec.modifiers, Modifier.ABSTRACT, Modifier.STATIC, Util.DEFAULT);
        requireExactlyOneOf(methodSpec.modifiers, Modifier.PUBLIC, Modifier.PRIVATE);
....
```

I don't understand this requirement 
according to the [Java 8 Spec](https://docs.oracle.com/javase/specs/jls/se8/html)
```
9.1.1.1. abstract Interfaces
Every interface is implicitly abstract.

9.4. Method Declarations
Every method declaration in the body of an interface is implicitly public (§6.6). It is permitted, but discouraged as a matter of style, to redundantly specify the public modifier for a method declaration in an interface.
An interface method lacking a default modifier or a static modifier is implicitly abstract
```
So maybe JavaPoet don't need to check this modifier

**Comment by JakeWharton** [comment]
Interfaces can have non-abstract methods so enforcing its presence ensures that the intent matches behavior. The same is true for public and private visibilities.

We enforce that you be explicit when telling JavaPoet what to emit an then we elide things like the 'public' visibility when generating the code because we know it's the default and we know it's what you explicitly meant (versus thinking you could emit package-scoped methods).

There's also some details in #531 about this.

**Comment by tiagorocha18** [comment]
I miss my cat
