### ISSUE TITLE
History of API changes for JavaPoet

### ISSUE THREAD

**Issue by lvc** [square/javapoet#584]
The review of API changes for the JavaPoet library since version 1.0.0: https://abi-laboratory.pro/java/tracker/timeline/javapoet/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/com/squareup/javapoet/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![javapoet-2](https://user-images.githubusercontent.com/1517837/31984258-8e0dfef4-b969-11e7-886a-b71a636f2632.png)

![javapoet-1](https://user-images.githubusercontent.com/1517837/31984259-8e2c5dd6-b969-11e7-9bf0-e900268048aa.png)

**Comment by JakeWharton** [comment]
Just some small feedback: the purported binary changes are technically correct but there isn't a problem because `TypeName` only has private or package-visible constructors which prevents subclassing. If we assume that no one is adding classes to our package (which I think is relatively safe) then we'd be at 100% for those two releases.

But this is really cool. Thanks for sharing!
