### ISSUE TITLE
Using block-style comments with JavaFile.addFileComment()

### ISSUE THREAD

**Issue by cilki** [square/javapoet#659]
~~I would like~~ I'm required to add a copyright header using a block-style comment, but `JavaFile.addFileComment(String)` always results in a line-style comment.

Here are my ideas:
- Detect whether the input is already a comment and simply write it out unchanged.

- Maybe the following pattern could emit a literal comment:
```
javaFile.addFileComment("$L", "/** blah **/");
```
I'm happy to submit a PR if either (or something else) would be acceptable.

**Comment by swankjesse** [comment]
This requirement doesn't make much sense. But if you need this, just concatenate your comment as a string with JavaPoet’s output!

**Comment by bjakke** [comment]
Hello,

Commenting here since this is something also I would have needed some time ago. I believe the intention was to output e.g. like in https://github.com/google/guava/blob/master/guava/src/com/google/common/base/CommonMatcher.java (the apache license header)

Sometimes the generated code is part of a project that bundes source code and a project might have requirement that all code file have a license header. Therefore this could be useful as proper API maybe. Given that JavaFile.writeTo takes root Path, I'm not sure how easy it would be to just add a String "prefix" to the source file that is to be written?

Personally I have used a maven plugin 
```
<groupId>com.mycila</groupId>
<artifactId>license-maven-plugin</artifactId>
```
to ensure all files have correct header in my own projects, but I also have a tool based on JavaPoet that currently can only offer line-style license header support.

Anyway thanks for making such a wonderful library!

**Comment by swankjesse** [comment]
It's weird to put a license header in a generated file.

**Comment by ewoks** [comment]
Actually, it's not so weird if we will use generated java files in other project
