### ISSUE TITLE
Support for Custom Code Styles

### ISSUE THREAD

**Issue by aarnaut** [square/javapoet#713]
Due to the code style standards we have at the company, I need to adapt some code properties such as:
* code indentation
* ordering of members inside a class

and many more.

I wanted to extend/use the already existing TypeSpec or some other classes, but they're all final and none implement from an interface. Is there some recommended way for customizing writers or should I check out the library and have a custom version (something I'd rather avoid)?

**Comment by JakeWharton** [comment]
The absence of customization we believe is a feature!

Formatting generated code rarely makes sense and you should get your company rules changed since you'll never be able to ensure all code generators conform to your style.

That being said, specifically, indentation can be changed on `JavaFile.Builder`. I once proposed the ability to accept a `Comparator` for ordering but it was deemed unnecessary and at this point I agree and am glad we didn't add it.

**Comment by Egorand** [comment]
The argument you can use is that your company's style standards most likely apply to _source_ code, and generated code is not considered source. In this way it's similar to bytecode.

**Comment by aarnaut** [comment]
The problem is that the code I'm generating _is_ source code. This is due to the design of the application, which requires quite a lot of boilerplate before 'real' code begins. I found this annoying, so I wanted to write a plugin that generates all this for me. Anyhow, thank you both for the replies!

**Comment by JakeWharton** [comment]
We have seen people use google-java-format to format the output. That of
course means that you need to be using the Google's Java code style though.

**Comment by ronshapiro** [comment]
Can you generate your code in a manner that allows it to be implementation details of the code you actually care about? If the code is boilerplate, you probably don't want to check it in either, as it would be hard to read. Then you don't need to care about the code style.
