### ISSUE TITLE
How to replace a Class in everywhere ?

### ISSUE THREAD

**Issue by shifujun** [square/javapoet#744]
I was generating a class with same methods of existing class. But I need to replace a type that existing class referred to another type. In everywhere, include method signature, method body. 

I can do this with Javassist, but it is byte-code editing. I prefer generate source code with javapoet.

Like this:
http://www.javassist.org/html/javassist/CtClass.html#replaceClassName(java.lang.String,java.lang.String)
```
public void replaceClassName​(java.lang.String oldName, java.lang.String newName)
Substitutes newName for all occurrences of a class name oldName in the class file.
Parameters:
oldName - replaced class name
newName - substituted class name
```

**Comment by JakeWharton** [comment]
There is no way to do this with JavaPoet. If you are switching from manipulating the class by using bytecode to manipulating it using source code I would recommend using [Spoon](http://spoon.gforge.inria.fr/) which is purpose-built for this task instead of JavaPoet which is designed for generating Java from things like schemas and in annotation processors.
