### ISSUE TITLE
String array support for code formatter

### ISSUE THREAD

**Issue by quintesse** [square/javapoet#847]
It would be nice to be able to do something like:

```
.addStatement("Arrays.asList($A)", someStrings)
```

and have that be expanded to:

```
Arrays.asList("one", "two", "three");
```

Right now I do:

```
String args = Stream.generate(() -> "$S").limit(someStrings.length).collect(Collectors.joining(","));
foo.addStatement("Arrays.asList(" + args + ")", someStrings);
```

**Comment by JakeWharton** [comment]
The current recommended way to do this is to aggregate `CodeBlock` instances in a list and then do `CodeBlock.join` (with a `%L` in the format string).

https://github.com/square/javapoet/blob/88517888277e3e92cbbdd054228f7f0ff68a841c/src/test/java/com/squareup/javapoet/CodeBlockTest.java#L305-L313

Because this is a test we just call `.toString()`, but you would use `%L` and pass the resulting `CodeBlock` instance.

In your specific example doing this is safer because the strings will have special characters escaped if you use `CodeBlock` correctly:
```java
var strings = List.of(
  CodeBlock.of("%S", "one"),
  CodeBlock.of("%S", "two\nthree"),
  CodeBlock.of("%S", "four"));
method.addStatement("return %T.asList(%L)", Arrays::class, CodeBlock.join(strings, ", "));
```
which will produce
```java
return Arrays.asList("one", "two\nthree", "four");
```

Also, bonus, you can use a wrapping space after the comma instead of a normal one and get line-wrapping!

**Comment by quintesse** [comment]
Ok, understood, but look at the amount of code you had to write for that against the simplicity of my suggestion ;-)

**Comment by JakeWharton** [comment]
I would say that's the general theme of JavaPoet (and Java itself). Correctness simply demands slightly more code.

Your proposal is broken for any string which requires escape sequences. Now you have to sanitize yourself. And eventually you'll want to reference something like a local variable or parameter name that will change your solution. Or use literals that are not strings, such as class references. The one with `CodeBlock` scales to anything you can generate.

The economics of writing a code generator are such that writing 20% more code once should not be a big deal. The amount of code you generate and are saved from writing by hand is orders of magnitude more.
